# Generated by Django 5.1.1 on 2025-01-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate_dimensions',
            field=models.CharField(blank=True, help_text='ابعاد شناسنامه به میلیمتر (طول*عرض)', max_length=50, null=True, verbose_name='ابعاد شناسنامه'),
        ),
        migrations.AddField(
            model_name='product',
            name='certificate_type',
            field=models.CharField(blank=True, help_text='نوع شناسنامه', max_length=255, null=True, verbose_name='نوع شناسنامه'),
        ),
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text='ابعاد به میلیمتر (طول*عرض*ارتفاع)', max_length=50, null=True, verbose_name='ابعاد'),
        ),
        migrations.AddField(
            model_name='product',
            name='thickness',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='ضخامت به میلیمتر', max_digits=5, null=True, verbose_name='ضخامت'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='وزن به گرم', max_digits=5, null=True, verbose_name='وزن'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='موجودی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='تاریخ بروزرسانی'),
        ),
    ]
